### ISSUE TITLE
is default merge strategy required?

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/github-auto-merge-skill#8]
<img width="640" alt="Screenshot 2020-05-08 14 13 38" src="https://user-images.githubusercontent.com/1643888/81449920-2f892500-9136-11ea-9aa0-adf00804a1a2.png">

If we leave "None selected", what is the default?

**Comment by cdupuis** [comment]
Default is none. We pass nothing to git.

**Comment by slimslenderslacks** [comment]
The github interface lists "squash and merge", "rebase and merge", and "create a merge commit".  For some reason, I was remembering that you can choose to do an ff merge if it's allowed.  So "none" is maybe "merge"?  Where the "merge" will be ff if possible and create merge commit otherwise.  I'm not sure if it helps to be explicit there but I suddenly found myself questioning whether I had misconfigured something

**Comment by cdupuis** [comment]
This is not the default auto merge policy. The screenshot is from auto rebase skill and we only offer Ours and Theirs as possible values. For merges git doesn’t require any merge strategy to be passed into rebase.

The documentation of this parameter it at https://github.com/atomist-skills/github-auto-rebase-skill#how-to-configure

**Comment by slimslenderslacks** [comment]
Yes, that's right, I think I logged this on the wrong repo.  Auto-rebase had the "merge commit" option, and I think I understood none-selected as being "use GitHub default".

For auto-rebase, I guess there's a default behavior that github also provides and I don't think I'm familiar with what that is.

**Comment by slimslenderslacks** [comment]
In general, I think I was just getting confused between "default" and "none selected" but the confusion was more serious for auto-rebase where I wasn't sure what the default behavior would be.

**Comment by cdupuis** [comment]
It’s not GitHub providing the default but git itself. The rebase skill is not using GitHub.

**Comment by slenderslack** [comment]
So "None selected" means that we'll use a default "merge" when rebasing the commits.  Is that right?
